---
- name: Download LLVM ({{ llvm_version }})
  get_url:
    url: "{{ llvm_url }}"
    dest: "{{ working_dir }}/{{ llvm_version }}.tar.gz"
    timeout: 30
  register: download_llvm
  retries: 5
  delay: 10
  until: download_llvm.status_code == 200
  

- name: Extract LLVM ({{ llvm_version }})
  unarchive:
    src: "{{ working_dir }}/{{ llvm_version }}.tar.gz"
    dest: "{{ working_dir }}"
    remote_src: yes
  when: download_llvm.changed

- name: Move LLVM ({{ llvm_version }})
  command: mv {{ working_dir }}/{{ llvm_path }} {{ llvm_dir }}
  args:
    creates: "{{ llvm_dir }}"

